"""add remaining tables from diagram

Revision ID: 20674abc0fc2
Revises: 84d29cadfb28
Create Date: 2026-10-06 16:51:20.618262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20674abc0fc2'
down_revision: Union[str, None] = '84d29cadfb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dominio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_dominio', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rubro', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ruta_formativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark',
    sa.Column('id_benchmark', sa.Integer(), nullable=False),
    sa.Column('promedio_puntaje', sa.Float(), nullable=True),
    sa.Column('mediana_puntaje', sa.Float(), nullable=True),
    sa.Column('puntaje_maximo', sa.Float(), nullable=True),
    sa.Column('puntaje_minimo', sa.Float(), nullable=True),
    sa.Column('total_evaluaciones', sa.Integer(), nullable=True),
    sa.Column('Rubro_id', sa.Integer(), nullable=True),
    sa.Column('dominio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Rubro_id'], ['rubro.id'], ),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominio.id'], ),
    sa.PrimaryKeyConstraint('id_benchmark')
    )
    op.create_table('catalogo_brechas',
    sa.Column('id_brecha', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('comportamiento_detectado', sa.Text(), nullable=True),
    sa.Column('criticidad', sa.Integer(), nullable=True),
    sa.Column('ruta_formativa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ruta_formativa_id'], ['ruta_formativa.id'], ),
    sa.PrimaryKeyConstraint('id_brecha')
    )
    op.create_table('usuario_temporal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_expiracion', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('validacion_invitacion', sa.String(length=1), nullable=True),
    sa.Column('Rubro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumen',
    sa.Column('id_resumen', sa.Integer(), nullable=False),
    sa.Column('puntaje_obtenido', sa.Float(), nullable=True),
    sa.Column('nivel_madurez', sa.String(length=10), nullable=True),
    sa.Column('total_controles_evaluados', sa.Integer(), nullable=True),
    sa.Column('Evaluacion_id', sa.Integer(), nullable=True),
    sa.Column('dominio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Evaluacion_id'], ['evaluacion.id'], ),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominio.id'], ),
    sa.PrimaryKeyConstraint('id_resumen')
    )
    op.create_foreign_key(None, 'evaluacion', 'usuario_temporal', ['Usuario_temporal_id'], ['id'])
    op.create_foreign_key(None, 'matriz_controles', 'dominio', ['dominio_id'], ['id'])
    op.create_foreign_key(None, 'respuestas', 'catalogo_brechas', ['Catalogo_brechas_id_brecha'], ['id_brecha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'respuestas', type_='foreignkey')
    op.drop_constraint(None, 'matriz_controles', type_='foreignkey')
    op.drop_constraint(None, 'evaluacion', type_='foreignkey')
    op.drop_table('resumen')
    op.drop_table('usuario_temporal')
    op.drop_table('catalogo_brechas')
    op.drop_table('benchmark')
    op.drop_table('ruta_formativa')
    op.drop_table('rubro')
    op.drop_table('dominio')
    # ### end Alembic commands ###
