"""init schema

Revision ID: 84d29cadfb28
Revises: 
Create Date: 2026-10-06 01:03:38.936789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d29cadfb28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('estado_progreso', sa.String(length=20), nullable=True),
    sa.Column('Usuario_temporal_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriz_controles',
    sa.Column('id_control', sa.Integer(), nullable=False),
    sa.Column('pregunta_evaluacion', sa.String(length=200), nullable=True),
    sa.Column('obligacion', sa.String(length=200), nullable=True),
    sa.Column('dominio_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_control')
    )
    op.create_table('respuestas',
    sa.Column('id_respuesta', sa.Integer(), nullable=False),
    sa.Column('estado_clasificacion', sa.String(length=20), nullable=True),
    sa.Column('justificacion_usuario', sa.Text(), nullable=True),
    sa.Column('Matriz_controles_id_control', sa.Integer(), nullable=True),
    sa.Column('Catalogo_brechas_id_brecha', sa.Integer(), nullable=True),
    sa.Column('Evaluacion_id', sa.Integer(), nullable=True),
    sa.Column('estado_clasificacion_final', sa.String(length=20), nullable=True),
    sa.Column('fuente_clasificacion', sa.String(length=10), nullable=True),
    sa.Column('confianza_clasificacion', sa.Float(), nullable=True),
    sa.Column('fecha_validacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Evaluacion_id'], ['evaluacion.id'], ),
    sa.ForeignKeyConstraint(['Matriz_controles_id_control'], ['matriz_controles.id_control'], ),
    sa.PrimaryKeyConstraint('id_respuesta')
    )
    op.create_table('evidencias',
    sa.Column('id_evidencia', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('hash_archivo', sa.String(length=64), nullable=False),
    sa.Column('estado_validacion', sa.String(length=20), nullable=False),
    sa.Column('clasificacion_llm', sa.String(length=20), nullable=True),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('justificacion_llm', sa.Text(), nullable=True),
    sa.Column('datos_extraidos', sa.JSON(), nullable=True),
    sa.Column('errores_validacion', sa.JSON(), nullable=True),
    sa.Column('fecha_subida', sa.Date(), nullable=True),
    sa.Column('fecha_procesada', sa.Date(), nullable=True),
    sa.Column('Respuestas_id_respuesta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Respuestas_id_respuesta'], ['respuestas.id_respuesta'], ),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    op.create_index(op.f('ix_evidencias_hash_archivo'), 'evidencias', ['hash_archivo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidencias_hash_archivo'), table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_table('respuestas')
    op.drop_table('matriz_controles')
    op.drop_table('evaluacion')
    # ### end Alembic commands ###
