"""extend matriz_controles and catalogo_brechas

Revision ID: b54cdc747a36
Revises: 20674abc0fc2
Create Date: 2026-10-06 17:13:42.361440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54cdc747a36'
down_revision: Union[str, None] = '20674abc0fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_brechas', sa.Column('codigo_brecha', sa.String(length=20), nullable=True))
    op.add_column('catalogo_brechas', sa.Column('accion_sistema', sa.String(length=100), nullable=True))
    op.alter_column('catalogo_brechas', 'criticidad',
                existing_type=sa.INTEGER(),
                type_=sa.String(length=10),
                existing_nullable=True,
                postgresql_using='criticidad::varchar')
    op.add_column('matriz_controles', sa.Column('codigo_control', sa.String(length=20), nullable=True))
    op.add_column('matriz_controles', sa.Column('framework_fuente', sa.String(length=50), nullable=True))
    op.add_column('matriz_controles', sa.Column('articulo_referencia', sa.String(length=100), nullable=True))
    op.add_column('matriz_controles', sa.Column('tipo_fuente', sa.String(length=50), nullable=True))
    op.add_column('matriz_controles', sa.Column('aplicabilidad', sa.String(length=100), nullable=True))
    op.add_column('matriz_controles', sa.Column('evidencia_esperada', sa.Text(), nullable=True))
    op.add_column('matriz_controles', sa.Column('criticidad', sa.String(length=10), nullable=True))
    op.add_column('matriz_controles', sa.Column('recomendacion', sa.Text(), nullable=True))
    op.add_column('matriz_controles', sa.Column('test_asociado', sa.String(length=100), nullable=True))
    op.add_column('matriz_controles', sa.Column('catalogo_brechas_id_brecha', sa.Integer(), nullable=True))
    op.alter_column('matriz_controles', 'pregunta_evaluacion',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_foreign_key(None, 'matriz_controles', 'catalogo_brechas', ['catalogo_brechas_id_brecha'], ['id_brecha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matriz_controles', type_='foreignkey')
    op.alter_column('matriz_controles', 'pregunta_evaluacion',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('matriz_controles', 'catalogo_brechas_id_brecha')
    op.drop_column('matriz_controles', 'test_asociado')
    op.drop_column('matriz_controles', 'recomendacion')
    op.drop_column('matriz_controles', 'criticidad')
    op.drop_column('matriz_controles', 'evidencia_esperada')
    op.drop_column('matriz_controles', 'aplicabilidad')
    op.drop_column('matriz_controles', 'tipo_fuente')
    op.drop_column('matriz_controles', 'articulo_referencia')
    op.drop_column('matriz_controles', 'framework_fuente')
    op.drop_column('matriz_controles', 'codigo_control')
    op.alter_column('catalogo_brechas', 'criticidad',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('catalogo_brechas', 'accion_sistema')
    op.drop_column('catalogo_brechas', 'codigo_brecha')
    # ### end Alembic commands ###
